#!/bin/bash


export RTL_ROOT="$(pwd)/../../rtl"
export GEN1_ROOT="$(pwd)/../../../../v1.0/rev2/rtl"
export V1S_ROOT="$GEN1_ROOT/v1_slave"
export V2COM_ROOT="$GEN1_ROOT/v2_common"

vlogan -sverilog  +v2k -full64 -timescale=1ps/1ps -f ../flist/ms.cf -l compile_ms1.log

vlogan -sverilog  +v2k -full64 -timescale=1ps/1ps +define+TIMESCALE_EN+VCS+BEHAVIORAL+MAIB_PIN96+ALTR_HPS_INTEL_MACROS_OFF   -f ../flist/sl_v1.cf -l compile_s1.log

vlogan -sverilog  +v2k -full64  -timescale=1ps/1ps +define+VCS+SL_AIB_GEN1 -f ../flist/tb_rtl.cf -l compile_tb.log

vcs -debug_acc+all -full64 +lint=TFIPC-L +error+100 +lint=PCWM  -top top_tb -l vcs.log
