+incdir+../aib_lib/aibcr3_lib/rtl/
+incdir+../aib_lib/aibcr3pnr_lib/rtl/
+incdir+../aib_lib/c3dfx/rtl/defines/
../aib_lib/c3lib/rtl/defines/c3lib_dv_defines.sv
../aib_lib/c3dfx/rtl/defines/c3dfx.vh

// pointer to standalone DCC - DCC, c3 and DLL pnr block
../aib_lib/aibcr3_lib/rtl/aibcr3_dcc_8ph_intp.v
../aib_lib/aibcr3_lib/rtl/aibcr3_dcc_crsdlyline.v
../aib_lib/aibcr3_lib/rtl/aibcr3_dcc_dll.v
../aib_lib/aibcr3_lib/rtl/aibcr3_dcc_dlyline64.v
../aib_lib/aibcr3_lib/rtl/aibcr3_dcc_dlyline.v
../aib_lib/aibcr3_lib/rtl/aibcr3_dcc_dly.v
../aib_lib/aibcr3_lib/rtl/aibcr3_dcc_gry2thm64.v
../aib_lib/aibcr3_lib/rtl/aibcr3_dcc_helper.v
../aib_lib/aibcr3_lib/rtl/aibcr3_dcc_interpolator.v
../aib_lib/aibcr3_lib/rtl/aibcr3_dcc_phasedet.v
../aib_lib/aibcr3_lib/rtl/aibcr3_dcc_top.v
../aib_lib/aibcr3_lib/rtl/aibcr3_dll_custom.v
../aib_lib/aibcr3_lib/rtl/aibcr3_dll_lock_dly.v
../aib_lib/aibcr3_lib/rtl/aibcr3_dlycell_dcc.v
../aib_lib/aibcr3_lib/rtl/aibcr3_svt16_scdffcdn_cust.v
../aib_lib/aibcr3_lib/rtl/aibcr3_svt16_scdffsdn_cust.v
../aib_lib/aibcr3_lib/rtl/aibcr3_ulvt16_2xarstsyncdff1_b2.v
../aib_lib/aibcr3_lib/rtl/aibcr3_ulvt16_dffcdn_cust.v
../aib_lib/aibcr3_lib/rtl/aibcr3_io_cmos_nand_x64.v

//aibcr3 model

../aib_lib/aibcr3_lib/rtl/aibcr3_top_wrp.v

// this section is for strobe align circuits

../aib_lib/aibcr3_lib/rtl/aibcr3_str_align.v
../aib_lib/aibcr3_lib/rtl/aibcr3_clktree_mimic.v
../aib_lib/aibcr3_lib/rtl/aibcr3_clktree.v
../aib_lib/aibcr3_lib/rtl/aibcr3_cmos_nand_x64.v
../aib_lib/aibcr3_lib/rtl/aibcr3_dll_8ph_intp.v
../aib_lib/aibcr3_lib/rtl/aibcr3_dll_dlyline64.v
../aib_lib/aibcr3_lib/rtl/aibcr3_dll_gry2thm64.v
../aib_lib/aibcr3_lib/rtl/aibcr3_dll_ibkmux.v
../aib_lib/aibcr3_lib/rtl/aibcr3_dlycell_dll.v
../aib_lib/aibcr3_lib/rtl/aibcr3_dlycell_dll_c.v

// other aibcr models
../aib_lib/aibcr3_lib/rtl/aibcr3_scan_iomux.v
../aib_lib/aibcr3_lib/rtl/aibcr3_2to4dec.v
../aib_lib/aibcr3_lib/rtl/aibcr3_analog.v
../aib_lib/aibcr3_lib/rtl/aibcr3_avmm1.v
../aib_lib/aibcr3_lib/rtl/aibcr3_avmm2.v
../aib_lib/aibcr3_lib/rtl/aibcr3_buffx1_top.v
../aib_lib/aibcr3_lib/rtl/aibcr3_buffx1.v
../aib_lib/aibcr3_lib/rtl/aibcr3_clktree_avmm_mimic.v
../aib_lib/aibcr3_lib/rtl/aibcr3_clktree_avmm_pcs.v
../aib_lib/aibcr3_lib/rtl/aibcr3_clktree_avmm.v
../aib_lib/aibcr3_lib/rtl/aibcr3_clktree_pcs.v
../aib_lib/aibcr3_lib/rtl/aibcr3_cmos_fine_dly.v
../aib_lib/aibcr3_lib/rtl/aibcr3_cmos_nand_x1.v
../aib_lib/aibcr3_lib/rtl/aibcr3_io_ip8phs.v
../aib_lib/aibcr3_lib/rtl/aibcr3_digital.v
../aib_lib/aibcr3_lib/rtl/aibcr3_inv_split_align.v
../aib_lib/aibcr3_lib/rtl/aibcr3_lvshift.v
../aib_lib/aibcr3_lib/rtl/aibcr3_preclkbuf.v
../aib_lib/aibcr3_lib/rtl/aibcr3_quadph_code_gen.v
../aib_lib/aibcr3_lib/rtl/aibcr3_rxanlg.v
../aib_lib/aibcr3_lib/rtl/aibcr3_rxdatapath_rx.v
../aib_lib/aibcr3_lib/rtl/aibcr3_rxdig.v
../aib_lib/aibcr3_lib/rtl/aibcr3_top.v
../aib_lib/aibcr3_lib/rtl/aibcr3_txanlg.v
../aib_lib/aibcr3_lib/rtl/aibcr3_txdatapath_tx.v
../aib_lib/aibcr3_lib/rtl/aibcr3_txdig.v
../aib_lib/aibcr3_lib/rtl/aibcr3_nd2d0_custom.v
../aib_lib/aibcr3_lib/rtl/aibcr3_split_align.v
../aib_lib/aibcr3_lib/rtl/structured.v

// NEW for converted RTL (removed logic cells)

../aib_lib/aibcr3_lib/rtl/aibcr3_ff_r.v
../aib_lib/aibcr3_lib/rtl/aibcr3_ff_p.v
../aib_lib/aibcr3_lib/rtl/aibcr3_ff_rp.v
../aib_lib/aibcr3_lib/rtl/aibcr3_latch.v


// NEW REL3.5

../aib_lib/aibcr3_lib/rtl/aibcr3_red_custom_dig.v
../aib_lib/aibcr3_lib/rtl/aibcr3_str_ff.v
../aib_lib/aibcr3_lib/rtl/aibcr3_sync_ff.v


//newly added

../aib_lib/aibcr3_lib/rtl/aibcr3_dcc_top_dummy.v
../aib_lib/aibcr3_lib/rtl/aibcr3_esd.v


//NEW REL4.0

../aib_lib/aibcr3_lib/rtl/aibcr3_str_ioload.v
../aib_lib/aibcr3_lib/rtl/aibcr3_red_custom_dig2.v
../aib_lib/aibcr3_lib/rtl/aibcr3_red_clkmux2.v
../aib_lib/aibcr3_lib/rtl/aibcr3_red_clkmux3.v
../aib_lib/aibcr3_lib/rtl/aibcr3_lvshift_lospeed.v
../aib_lib/aibcr3_lib/rtl/aibcr3_lvshift_diff.v
../aib_lib/aibcr3_lib/rtl/aibcr3_triinv_dig.v
../aib_lib/aibcr3_lib/rtl/aibcr3_interface.v
../aib_lib/aibcr3_lib/rtl/aibcr3_rambit_buf.v
../aib_lib/aibcr3_lib/rtl/aibcr3_signal_buf.v
../aib_lib/aibcr3_lib/rtl/aibcr3_data_buf.v
../aib_lib/aibcr3_lib/rtl/aibcr3_rxdat_mimic.v
../aib_lib/aibcr3_lib/rtl/aibcr3_txdat_mimic.v


../aib_lib/aibcr3_lib/rtl/aibcr3_dcc_dly_rep.v
../aib_lib/aibcr3_lib/rtl/aibcr3_dly_mimic.v
../aib_lib/aibcr3_lib/rtl/aibcr3_io_cmos_8ph_interpolator_rep.v
../aib_lib/aibcr3_lib/rtl/aibcr3_io_cmos_8ph_interpolator.v
../aib_lib/aibcr3_lib/rtl/aibcr3_io_nand_delay_line_min_rep.v

//copied models due to io_common_custom ND and CR conflict

../aib_lib/aibcr3_lib/rtl/aibcr3_io_cmos_nand_x1.v
../aib_lib/aibcr3_lib/rtl/aibcr3_io_cmos_nand_x128.v
../aib_lib/aibcr3_lib/rtl/aibcr3_io_nand_delay_line_min.v
../aib_lib/aibcr3_lib/rtl/aibcr3_io_nand_x128_delay_line.v

//NEW REL4.5
../aib_lib/aibcr3_lib/rtl/aibcr3_clkmux2.v


//NEW REL4.5 (replacing syncronizer- 3rd party cell issue)

../aib_lib/aibcr3_lib/rtl/aibcr3_sync_2ff.v
../aib_lib/aibcr3_lib/rtl/aibcr3_sync_3ff.v

//custom alias model

../aib_lib/aibcr3_lib/rtl/aibcr3_aliasv.v
../aib_lib/aibcr3_lib/rtl/aibcr3_aliasd.v


../aib_lib/aibcr3_lib/rtl/aibcr3_ulvt16_dffsdn_cust.v

// custom esd cells used outside of aibio and aibaux. sits in xcvrcntl
../aib_lib/aibcr3_lib/rtl/aibcr3_opio_esd.v
../aib_lib/aibcr3_lib/rtl/aibcr3_anaio_esd.v

// update for conformal
../aib_lib/aibcr3_lib/rtl/aibcr3_dlycell_dcc_rep.v

../aib_lib/c3lib/rtl/basic/pulse_stretch/cdclib_pulse_stretch.sv

../aib_lib/c3lib/rtl/avmm/c3_avmm_rdl_intf.sv
../aib_lib/c3lib/rtl/avmm/c3lib_cfgcsr_fastslow_pulse_meta.sv
../aib_lib/c3lib/rtl/avmm/c3lib_cfgcsr_slowfast_pulse_meta.sv
../aib_lib/c3lib/rtl/avmm/c3lib_avmm_pulse_cross.sv

../aib_lib/c3lib/rtl/cdc/async_fifo/c3lib_async_fifo.sv

../aib_lib/c3lib/rtl/cdc/bit_synchronizer/c3lib_bitsync.sv
../aib_lib/c3lib/rtl/cdc/bit_synchronizer/c3lib_sync2_lvt_bitsync.sv
../aib_lib/c3lib/rtl/cdc/bit_synchronizer/c3lib_sync2_ulvt_bitsync.sv
../aib_lib/c3lib/rtl/cdc/bit_synchronizer/c3lib_sync3_ulvt_bitsync.sv
../aib_lib/c3lib/rtl/cdc/gray_code/c3lib_bintogray.sv
../aib_lib/c3lib/rtl/cdc/gray_code/c3lib_graytobin.sv
../aib_lib/c3lib/rtl/cdc/level_synchronizer/c3lib_lvlsync.sv
../aib_lib/c3lib/rtl/cdc/reset_synchronizer/c3lib_rstsync.sv
../aib_lib/c3lib/rtl/cdc/vector_synchronizer/c3lib_vecsync.sv
../aib_lib/c3lib/rtl/cdc/vector_synchronizer/c3lib_vecsync_handshake.sv
../aib_lib/c3lib/rtl/cdc/glitch_free_mux/c3lib_gf_clkmux.sv

../aib_lib/c3lib/rtl/ctn/clock_buf/c3lib_ckinv_ctn.sv
../aib_lib/c3lib/rtl/ctn/clock_buf/c3lib_ckbuf_ctn.sv
../aib_lib/c3lib/rtl/ctn/clock_buf/c3lib_ckand2_ctn.sv
../aib_lib/c3lib/rtl/ctn/clock_gater/c3lib_ckg_async_posedge_ctn.sv
../aib_lib/c3lib/rtl/ctn/clock_gater/c3lib_ckg_negedge_ctn.sv
../aib_lib/c3lib/rtl/ctn/clock_gater/c3lib_ckg_posedge_ctn.sv
../aib_lib/c3lib/rtl/ctn/clock_mux/c3lib_mux2_ctn.sv
../aib_lib/c3lib/rtl/ctn/clock_mux/c3lib_mux3_ctn.sv
../aib_lib/c3lib/rtl/ctn/clock_mux/c3lib_mux4_ctn.sv
../aib_lib/c3lib/rtl/ctn/clock_divider/c3lib_ckdiv2_ctn.sv
../aib_lib/c3lib/rtl/ctn/clock_divider/c3lib_ckdiv4_ctn.sv
../aib_lib/c3lib/rtl/ctn/clock_divider/c3lib_ckdiv8_ctn.sv

../aib_lib/c3lib/rtl/lcell/c3lib_and2_lcell.sv
../aib_lib/c3lib/rtl/lcell/c3lib_buf_lcell.sv
../aib_lib/c3lib/rtl/lcell/c3lib_mux2_lcell.sv
../aib_lib/c3lib/rtl/lcell/c3lib_nand2_lcell.sv
../aib_lib/c3lib/rtl/lcell/c3lib_or2_lcell.sv
../aib_lib/c3lib/rtl/lcell/c3lib_tie_bus_lcell.sv
../aib_lib/c3lib/rtl/lcell/c3lib_tieh_lcell.sv
../aib_lib/c3lib/rtl/lcell/c3lib_tiel_lcell.sv
../aib_lib/c3lib/rtl/lcell/c3lib_mtieh_lcell.sv
../aib_lib/c3lib/rtl/lcell/c3lib_mtiel_lcell.sv
../aib_lib/c3lib/rtl/lcell/c3lib_dff_scan_lcell.sv

../aib_lib/c3lib/rtl/ecc/c3lib_ecc_dec_c39_d32.sv
../aib_lib/c3lib/rtl/ecc/c3lib_ecc_dec_c88_d80.sv
../aib_lib/c3lib/rtl/ecc/c3lib_ecc_enc_d32_c39.sv
../aib_lib/c3lib/rtl/ecc/c3lib_ecc_enc_d80_c88.sv

../aib_lib/c3lib/rtl/primitives/c3lib_sync2_reset_lvt_gate.sv
../aib_lib/c3lib/rtl/primitives/c3lib_sync2_reset_ulvt_gate.sv
../aib_lib/c3lib/rtl/primitives/c3lib_sync3_reset_ulvt_gate.sv
../aib_lib/c3lib/rtl/primitives/c3lib_sync2_set_lvt_gate.sv
../aib_lib/c3lib/rtl/primitives/c3lib_sync2_set_ulvt_gate.sv
../aib_lib/c3lib/rtl/primitives/c3lib_sync3_set_ulvt_gate.sv
../aib_lib/c3lib/rtl/primitives/c3lib_tie0_svt_1x.sv
../aib_lib/c3lib/rtl/primitives/c3lib_tie1_svt_1x.sv
../aib_lib/c3lib/rtl/primitives/c3lib_mtie0_ds.sv
../aib_lib/c3lib/rtl/primitives/c3lib_mtie1_ds.sv
../aib_lib/c3lib/rtl/primitives/c3lib_or2_svt_2x.sv
../aib_lib/c3lib/rtl/primitives/c3lib_nand2_svt_2x.sv
../aib_lib/c3lib/rtl/primitives/c3lib_mux2_svt_2x.sv
../aib_lib/c3lib/rtl/primitives/c3lib_ckmux4_ulvt_gate.sv
../aib_lib/c3lib/rtl/primitives/c3lib_ckmux4_lvt_gate.sv
../aib_lib/c3lib/rtl/primitives/c3lib_ckinv_lvt_12x.sv
../aib_lib/c3lib/rtl/primitives/c3lib_ckinv_svt_8x.sv
../aib_lib/c3lib/rtl/primitives/c3lib_ckg_lvt_8x.sv
../aib_lib/c3lib/rtl/primitives/c3lib_ckbuf_lvt_4x.sv
../aib_lib/c3lib/rtl/primitives/c3lib_buf_svt_4x.sv
../aib_lib/c3lib/rtl/primitives/c3lib_and2_svt_2x.sv
../aib_lib/c3lib/rtl/primitives/c3lib_and2_svt_4x.sv
../aib_lib/c3lib/rtl/primitives/c3lib_dff0_reset_lvt_2x.sv
../aib_lib/c3lib/rtl/primitives/c3lib_dff0_set_lvt_2x.sv
../aib_lib/c3lib/rtl/primitives/c3lib_dff0_scan_reset_svt_2x.sv
../aib_lib/c3lib/rtl/primitives/c3lib_sync_metastable_behav_gate.sv

../aib_lib/c3dfx/rtl/tcm/c3dfx_tcm_wrap.sv
../aib_lib/c3dfx/rtl/tcm/c3dfx_tcm.sv
../aib_lib/c3aibadapt/rtl/c3aibadapt.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_avmm/c3aibadapt_avmm1_async.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_avmm/c3aibadapt_avmm1clk_ctl.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_avmm/c3aibadapt_avmm1_config.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_avmm/c3aibadapt_hwcfg_dec.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_avmm/c3aibadapt_cfg_csr.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_avmm/c3aibadapt_usr_csr.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_avmm/c3aibadapt_avmm1_transfer.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_avmm/c3aibadapt_avmm1.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_avmm/c3aibadapt_avmm2_async.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_avmm/c3aibadapt_avmm2clk_ctl.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_avmm/c3aibadapt_avmm2_config.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_avmm/c3aibadapt_avmm2_transfer.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_avmm/c3aibadapt_avmm2.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_avmm/c3aibadapt_avmm_async.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_avmm/c3aibadapt_cfg_rdmux.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_avmm/c3aibadapt_avmmclk_dcg.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_avmm/c3aibadapt_avmmclk_gate.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_avmm/c3aibadapt_avmm_cmdbuilder.sv
../aib_lib/c3aibadapt/rtl/c3aibadapt_avmm/c3aibadapt_avmm_dec_arb.sv
../aib_lib/c3aibadapt/rtl/c3aibadapt_avmm/c3aibadapt_avmm_decode.sv
../aib_lib/c3aibadapt/rtl/c3aibadapt_avmm/c3aibadapt_avmm_rdfifo.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_avmm/c3aibadapt_avmmrst_ctl.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_avmm/c3aibadapt_avmm_usr32_exp.sv
../aib_lib/c3aibadapt/rtl/c3aibadapt_avmm/c3aibadapt_avmm.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_avmm/c3aibadapt_hrdrst_clkctl.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_avmm/c3aibadapt_hrdrst_rstctrl.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_cmn/c3aibadapt_cmn_async_capture_bit.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_cmn/c3aibadapt_cmn_async_capture_bus.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_cmn/c3aibadapt_cmn_clkand2.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_cmn/c3aibadapt_cmn_clkgate_high.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_cmn/c3aibadapt_cmn_clkgate.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_cmn/c3aibadapt_cmn_clkinv.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_cmn/c3aibadapt_cmn_clkmux2_cell.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_cmn/c3aibadapt_cmn_clkmux2.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_cmn/c3aibadapt_cmn_cp_comp_cntr.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_cmn/c3aibadapt_cmn_cp_dist_dw.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_cmn/c3aibadapt_cmn_cp_dist_pair_dw.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_cmn/c3aibadapt_cmn_cp_dist_pair.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_cmn/c3aibadapt_cmn_cp_dist.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_cmn/c3aibadapt_cmn_dft_clk_ctlr.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_cmn/c3aibadapt_cmn_latency_measure.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_cmn/c3aibadapt_cmn_occ_clkgate.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_cmn/c3aibadapt_cmn_occ_enable_logic.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_cmn/c3aibadapt_cmn_occ_gray_cntr.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_cmn/c3aibadapt_cmn_occ_test_ctlregs.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_cmn/c3aibadapt_cmn_parity_checker.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_cmn/c3aibadapt_cmn_parity_gen.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_cmn/c3aibadapt_cmn_pulse_stretch.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_cmn/c3aibadapt_cmn_dprio_status_sync_regs.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_cmn/c3aibadapt_cmn_shadow_status_regs.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_rxchnl/c3aibadapt_rxasync_capture.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_rxchnl/c3aibadapt_rxasync_direct.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_rxchnl/c3aibadapt_rxasync_rsvd_capture.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_rxchnl/c3aibadapt_rxasync_rsvd_update.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_rxchnl/c3aibadapt_rxasync_update.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_rxchnl/c3aibadapt_rxasync.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_rxchnl/c3aibadapt_rxchnl_testbus.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_rxchnl/c3aibadapt_rxchnl.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_rxchnl/c3aibadapt_rxclk_ctl.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_rxchnl/c3aibadapt_rxclk_gate.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_rxchnl/c3aibadapt_rxdp_asn.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_rxchnl/c3aibadapt_rxdp_async_fifo.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_rxchnl/c3aibadapt_rxdp_cp_bond.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_rxchnl/c3aibadapt_rxdp_del_sm.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_rxchnl/c3aibadapt_rxdp_fifo_ptr.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_rxchnl/c3aibadapt_rxdp_fifo_ram.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_rxchnl/c3aibadapt_rxdp_fifo.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_rxchnl/c3aibadapt_rxdp_map.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_rxchnl/c3aibadapt_rx_dprio.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_rxchnl/c3aibadapt_rxdp_rxeq_sm.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_rxchnl/c3aibadapt_rxdp_txeq_sm.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_rxchnl/c3aibadapt_rxdp_txeq.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_rxchnl/c3aibadapt_rxdp.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_rxchnl/c3aibadapt_rxrst_ctl.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_sr/c3aibadapt_fsr_in.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_sr/c3aibadapt_fsr_out.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_sr/c3aibadapt_sr_async_capture_bit.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_sr/c3aibadapt_sr_async_capture_bus.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_sr/c3aibadapt_srclk_ctl.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_sr/c3aibadapt_sr_in_bit.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_sr/c3aibadapt_sr_out_bit.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_sr/c3aibadapt_srrst_ctl.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_sr/c3aibadapt_sr_sm.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_sr/c3aibadapt_sr.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_sr/c3aibadapt_ssr_in.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_sr/c3aibadapt_ssr_out.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_txchnl/c3aibadapt_async_update.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_txchnl/c3aibadapt_hip_async_capture.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_txchnl/c3aibadapt_hip_async_update.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_txchnl/c3aibadapt_txasync_capture.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_txchnl/c3aibadapt_txasync_direct.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_txchnl/c3aibadapt_txasync_rsvd_capture.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_txchnl/c3aibadapt_txasync_rsvd_update.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_txchnl/c3aibadapt_txasync_update.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_txchnl/c3aibadapt_txasync.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_txchnl/c3aibadapt_txchnl_testbus.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_txchnl/c3aibadapt_txchnl.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_txchnl/c3aibadapt_txclk_ctl.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_txchnl/c3aibadapt_txclk_gate.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_txchnl/c3aibadapt_txdp_async_fifo.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_txchnl/c3aibadapt_txdp_cp_bond.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_txchnl/c3aibadapt_txdp_fifo_ptr.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_txchnl/c3aibadapt_txdp_fifo_ram.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_txchnl/c3aibadapt_txdp_fifo.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_txchnl/c3aibadapt_txdp_map.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_txchnl/c3aibadapt_tx_dprio.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_txchnl/c3aibadapt_txdp.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_txchnl/c3aibadapt_txdp_word_align.v
../aib_lib/c3aibadapt/rtl/c3aibadapt_txchnl/c3aibadapt_txrst_ctl.v

../aib_lib/aibcr3pnr_lib/rtl/aibcr3pnr_redundancy.v
../aib_lib/aibcr3pnr_lib/rtl/aibcr3pnr_jtag_bscan.v
../aib_lib/aibcr3pnr_lib/rtl/aibcr3pnr_bsr_red_wrap.v

../aib_lib/aibcr3pnr_lib/rtl/aibcr3pnr_half_cycle_code_gen.v
../aib_lib/aibcr3pnr_lib/rtl/aibcr3pnr_self_lock_assertion.v
../aib_lib/aibcr3pnr_lib/rtl/aibcr3pnr_dll_ctrl.v
../aib_lib/aibcr3pnr_lib/rtl/aibcr3pnr_dll_core.v
../aib_lib/aibcr3pnr_lib/rtl/aibcr3pnr_dll_pnr.v
../aib_lib/aibcr3pnr_lib/rtl/aibcr3pnr_rstsync.sv

../aib_lib/c3dfx/rtl/tcb/c3dfx_aibadaptwrap_tcb.sv
../aib_lib/c3aibadapt_wrap/rtl/c3aibadapt_wrap.v
../aib_lib/c3aibadapt_wrap/rtl/c3aib_master.sv
+incdir+../rtl/
+incdir+../ndsimslv/

../rtl/aib_dcc.v
../rtl/aib_aux_channel.v
../rtl/aib_aliasd.v
../rtl/aib_bitsync.v
../rtl/aib_bsr_red_wrap.v
../rtl/aib_buffx1_top.v
../rtl/aib_io_buffer.sv
../rtl/aib_ioring.v
../rtl/aib_jtag_bscan.v
../rtl/aib_mux21.v
../rtl/aib_osc_clk.sv
../rtl/aib_redundancy.v
../rtl/aib_rstnsync.v
../rtl/aib_sm.v
../rtl/aib_sr_ms.v
../rtl/aib_sr_sl.v
../rtl/dll.sv
../rtl/aib_channel.v
../rtl/aib.v

+incdir+../maib_rtl/cfg_shared/rtl/block_function/hdpldadapt/rtl/block_function
+incdir+../maib_rtl/cfg_shared/rtl/block_function/cdclib/rtl/block_function
+incdir+../maib_rtl/cfg_shared/rtl/block_function/cfg_shared/rtl/block_function
+incdir+../maib_rtl/aibnd_lib/rtl/block_function
+incdir+../maib_rtl/io_common_custom/rtl/block_function
+incdir+../maib_rtl/aibndpnr_lib/rtl/block_function
+incdir+../maib_rtl/cdclib/rtl/block_function
../maib_rtl/s10aib/rtl/ndaibadapt_wrap.v
../maib_rtl/s10aib/rtl/an.v
../maib_rtl/s10aib/rtl/s10aib.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_avmm/hdpldadapt_avmm1_async.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_avmm/hdpldadapt_avmm1_config.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_avmm/hdpldadapt_avmm1_dprio_mapping.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_avmm/hdpldadapt_avmm1_transfer.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_avmm/hdpldadapt_avmm1.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_avmm/hdpldadapt_avmm2_async.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_avmm/hdpldadapt_avmm2_transfer.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_avmm/hdpldadapt_avmm2.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_avmm/hdpldadapt_avmm_async_update.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_avmm/hdpldadapt_avmmclk_ctl.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_avmm/hdpldadapt_avmm_cmdfifo.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_avmm/hdpldadapt_avmm_cmn_intf.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_avmm/hdpldadapt_avmm_dprio_reg.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_avmm/hdpldadapt_avmm_rdfifo.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_avmm/hdpldadapt_avmmrst_ctl.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_avmm/hdpldadapt_avmm.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_avmm/hdpldadapt_avmm_async.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_avmm/hdpldadapt_hrdrst_rstctrl.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_avmm/hdpldadapt_hrdrst_clkctl.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_sr/hdpldadapt_fsr_in.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_sr/hdpldadapt_fsr_out.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_sr/hdpldadapt_srclk_ctl.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_sr/hdpldadapt_sr_in_bit.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_sr/hdpldadapt_sr_out_bit.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_sr/hdpldadapt_srrst_ctl.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_sr/hdpldadapt_sr_sm.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_sr/hdpldadapt_sr.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_sr/hdpldadapt_ssr_in.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_sr/hdpldadapt_ssr_out.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_tx_chnl/hdpldadapt_async_update.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_tx_chnl/hdpldadapt_tx_async_reserved_capture.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_tx_chnl/hdpldadapt_tx_async_reserved_update.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_tx_chnl/hdpldadapt_hip_async_capture.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_tx_chnl/hdpldadapt_hip_async_update.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_tx_chnl/hdpldadapt_tx_async_capture.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_tx_chnl/hdpldadapt_tx_async_direct.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_tx_chnl/hdpldadapt_tx_async_update.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_tx_chnl/hdpldadapt_tx_async.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_tx_chnl/hdpldadapt_tx_chnl.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_tx_chnl/hdpldadapt_txclk_ctl.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_tx_chnl/hdpldadapt_tx_datapath_async_fifo.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_tx_chnl/hdpldadapt_tx_datapath_fifo_ram.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_tx_chnl/hdpldadapt_tx_datapath_fifo_pointers.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_tx_chnl/hdpldadapt_tx_chnl_testbus.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_tx_chnl/hdpldadapt_tx_datapath_cp_bond.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_tx_chnl/hdpldadapt_tx_datapath_dv_gen.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_tx_chnl/hdpldadapt_tx_datapath_fifo.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_tx_chnl/hdpldadapt_tx_datapath_frame_gen.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_tx_chnl/hdpldadapt_tx_datapath.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_tx_chnl/hdpldadapt_tx_datapath_word_mark.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_tx_chnl/hdpldadapt_txrst_ctl.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_tx_chnl/hdpldadapt_tx_datapath_pulse_stretch.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_rx_chnl/hdpldadapt_rx_async_reserved_capture.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_rx_chnl/hdpldadapt_rx_async_reserved_update.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_rx_chnl/hdpldadapt_rx_async_capture.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_rx_chnl/hdpldadapt_rx_async_direct.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_rx_chnl/hdpldadapt_rx_async_update.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_rx_chnl/hdpldadapt_rx_async.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_rx_chnl/hdpldadapt_rx_chnl.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_rx_chnl/hdpldadapt_rxclk_ctl.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_rx_chnl/hdpldadapt_rx_datapath_asn.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_rx_chnl/hdpldadapt_rx_datapath_async_fifo.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_rx_chnl/hdpldadapt_rx_datapath_cp_bond.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_rx_chnl/hdpldadapt_rx_datapath_fifo.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_rx_chnl/hdpldadapt_rx_datapath_fifo_ram.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_rx_chnl/hdpldadapt_rx_datapath_fifo_pointers.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_rx_chnl/hdpldadapt_rx_datapath_insert_sm.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_rx_chnl/hdpldadapt_rx_datapath_del_sm.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_rx_chnl/hdpldadapt_rx_datapath.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_rx_chnl/hdpldadapt_rx_datapath_word_align.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_rx_chnl/hdpldadapt_rxrst_ctl.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_rx_chnl/hdpldadapt_rx_datapath_pulse_stretch.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_rx_chnl/hdpldadapt_rx_chnl_testbus.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_cmn/hdpldadapt_cmn_async_capture_bit.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_cmn/hdpldadapt_cmn_cp_comp_cntr.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_cmn/hdpldadapt_cmn_cp_dist_pair_dw.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_cmn/hdpldadapt_cmn_cp_dist.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_cmn/hdpldadapt_cmn_async_capture_bus.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_cmn/hdpldadapt_cmn_cp_dist_dw.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_cmn/hdpldadapt_cmn_cp_dist_pair.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_cmn/hdpldadapt_cmn_latency_measure.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_cmn/hdpldadapt_cmn_pulse_stretch.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_cmn/hdpldadapt_cmn_parity_gen.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_cmn/hdpldadapt_cmn_parity_checker.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_cmn/hdpldadapt_cmn_clkand2.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_cmn/hdpldadapt_cmn_clkdelay_map.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_cmn/hdpldadapt_cmn_clkdelay.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_cmn/hdpldadapt_cmn_clkdelay_cell.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_cmn/hdpldadapt_cmn_clkgate.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_cmn/hdpldadapt_cmn_clkinv.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_cmn/hdpldadapt_cmn_clkmux2_cell.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_cmn/hdpldadapt_cmn_clkmux2.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_cmn/hdpldadapt_cmn_clkor2.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_cmn/hdpldadapt_cmn_dft_clock_controller.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_cmn/hdpldadapt_cmn_occ_clkgate.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_cmn/hdpldadapt_cmn_occ_enable_logic.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_cmn/hdpldadapt_cmn_occ_gray_code_counter.v
../maib_rtl/hdpldadapt/rtl/hdpldadapt_cmn/hdpldadapt_cmn_occ_test_control_register.v
../maib_rtl/cdclib/rtl/block_function/cdclib_bintogray.v
../maib_rtl/cdclib/rtl/block_function/cdclib_bintogray_inc8.v
../maib_rtl/cdclib/rtl/block_function/cdclib_bitsync2.v
../maib_rtl/cdclib/rtl/block_function/cdclib_sync2_reset_type_l_gate.v
../maib_rtl/cdclib/rtl/block_function/cdclib_sync2_reset_type_n_gate.v
../maib_rtl/cdclib/rtl/block_function/cdclib_sync2_reset_type_w_gate.v
../maib_rtl/cdclib/rtl/block_function/cdclib_sync2_set_type_l_gate.v
../maib_rtl/cdclib/rtl/block_function/cdclib_sync2_set_type_n_gate.v
../maib_rtl/cdclib/rtl/block_function/cdclib_sync2_set_type_w_gate.v
../maib_rtl/cdclib/rtl/block_function/cdclib_bitsync4.v
../maib_rtl/cdclib/rtl/block_function/cdclib_sync4_reset_type_l_gate.v
../maib_rtl/cdclib/rtl/block_function/cdclib_sync4_reset_type_w_gate.v
../maib_rtl/cdclib/rtl/block_function/cdclib_sync4_set_type_l_gate.v
../maib_rtl/cdclib/rtl/block_function/cdclib_sync4_set_type_w_gate.v
../maib_rtl/cdclib/rtl/block_function/cdclib_graytobin.v
../maib_rtl/cdclib/rtl/block_function/cdclib_graytobin_inc2.v
../maib_rtl/cdclib/rtl/block_function/cdclib_graytobin_inc8.v
../maib_rtl/cdclib/rtl/block_function/cdclib_rst_n_sync.v
../maib_rtl/cdclib/rtl/block_function/cdclib_rst_n_sync_core.v
../maib_rtl/cfg_shared/rtl/block_function/cfg_dprio_csr_reg_bit.v
../maib_rtl/cfg_shared/rtl/block_function/cfg_dprio_csr_reg_nbits.v
../maib_rtl/cfg_shared/rtl/block_function/cfg_dprio_csr_reg_nregs.v
../maib_rtl/cfg_shared/rtl/block_function/cfg_cmn_non_scan_reg.v
../maib_rtl/cfg_shared/rtl/block_function/cfg_dprio_readdata_mux.v
../maib_rtl/cfg_shared/rtl/block_function/cfg_dprio_ctrl_stat_interface_top.v
../maib_rtl/cfg_shared/rtl/block_function/cfg_dprio_csr_test_mux.v
../maib_rtl/cfg_shared/rtl/block_function/cfg_cmn_clk_mux.v
../maib_rtl/cfg_shared/rtl/block_function/cfg_dprio_ctrl_reg_bit.v
../maib_rtl/cfg_shared/rtl/block_function/cfg_dprio_ctrl_reg_nbits.v
../maib_rtl/cfg_shared/rtl/block_function/cfg_dprio_ctrl_reg_nregs.v
../maib_rtl/cfg_shared/rtl/block_function/cfg_dprio_ctrl_stat_reg_chnl.v
../maib_rtl/cfg_shared/rtl/block_function/cfg_dprio_ctrl_stat_reg_top.v
../maib_rtl/cfg_shared/rtl/block_function/cfg_dprio_dis_ctrl_cvp.v
../maib_rtl/cfg_shared/rtl/block_function/cfg_dprio_readdata_sel.v
../maib_rtl/cfg_shared/rtl/block_function/cfg_dprio_status_reg_nbits.v
../maib_rtl/cfg_shared/rtl/block_function/cfg_dprio_status_reg_nregs.v
../maib_rtl/cfg_shared/rtl/block_function/cfg_dprio_status_sync_regs.v
../maib_rtl/cfg_shared/rtl/block_function/cfg_dprio_shadow_status_regs.v
../maib_rtl/cfg_shared/rtl/block_function/cfg_dprio_shadow_status_nregs.v
../maib_rtl/aibnd_lib/rtl/block_function/aibnd_top_wrp.v
../maib_rtl/aibnd_lib/rtl/block_function/aibnd_top.v
../maib_rtl/aibnd_lib/rtl/block_function/aibnd_dcc_dly_rep.v
../maib_rtl/aibnd_lib/rtl/block_function/aibnd_dly_mimic.v
../maib_rtl/aibnd_lib/rtl/block_function/aibnd_io_dly_interpolator_rep.v
../maib_rtl/aibnd_lib/rtl/block_function/aibnd_io_nand_delay_line_min_rep.v
../maib_rtl/aibnd_lib/rtl/block_function/aibnd_latch.v
../maib_rtl/aibnd_lib/rtl/block_function/aibnd_hgy_latch.v
../maib_rtl/aibnd_lib/rtl/block_function/aibnd_ff_r.v
../maib_rtl/aibnd_lib/rtl/block_function/aibnd_ff_rp.v
../maib_rtl/aibnd_lib/rtl/block_function/aibnd_2ff_scan.v
../maib_rtl/aibnd_lib/rtl/block_function/aibnd_aliasd.v
../maib_rtl/aibnd_lib/rtl/block_function/aibnd_aliasv.v
../maib_rtl/aibnd_lib/rtl/block_function/aibnd_2to4dec.v
../maib_rtl/aibnd_lib/rtl/block_function/aibnd_analog.v
../maib_rtl/aibnd_lib/rtl/block_function/aibnd_avmm1.v
../maib_rtl/aibnd_lib/rtl/block_function/aibnd_avmm2.v
../maib_rtl/aibnd_lib/rtl/block_function/aibnd_buffx1_top.v
../maib_rtl/aibnd_lib/rtl/block_function/aibnd_buffx1.v
../maib_rtl/aibnd_lib/rtl/block_function/aibnd_clkbuf.v
../maib_rtl/aibnd_lib/rtl/block_function/aibnd_clktree.v
../maib_rtl/aibnd_lib/rtl/block_function/aibnd_clktree_avmm.v
../maib_rtl/aibnd_lib/rtl/block_function/aibnd_clktree_avmm_mimic.v
../maib_rtl/aibnd_lib/rtl/block_function/aibnd_clktree_avmm_pcs.v
../maib_rtl/aibnd_lib/rtl/block_function/aibnd_clktree_mimic.v
../maib_rtl/aibnd_lib/rtl/block_function/aibnd_clktree_pcs.v
../maib_rtl/aibnd_lib/rtl/block_function/aibnd_cmos_fine_dly.v
../maib_rtl/aibnd_lib/rtl/block_function/aibnd_cmos_nand_x6.v
../maib_rtl/aibnd_lib/rtl/block_function/aibnd_cmos_nand_x1.v
../maib_rtl/aibnd_lib/rtl/block_function/aibnd_d8xsesdd1.v
../maib_rtl/aibnd_lib/rtl/block_function/aibnd_d8xsesdd2.v
../maib_rtl/aibnd_lib/rtl/block_function/aibnd_dcc_5b_b2tc_x1.v
../maib_rtl/aibnd_lib/rtl/block_function/aibnd_dcc_5b_b2tc.v
../maib_rtl/aibnd_lib/rtl/block_function/aibnd_dcc_dll.v
../maib_rtl/aibnd_lib/rtl/block_function/aibnd_dcc_ff.v
../maib_rtl/aibnd_lib/rtl/block_function/aibnd_dcc_fine_dly.v
../maib_rtl/aibnd_lib/rtl/block_function/aibnd_dcc_mux.v
../maib_rtl/aibnd_lib/rtl/block_function/aibnd_dcc_top.v
../maib_rtl/aibnd_lib/rtl/block_function/aibnd_digital.v
../maib_rtl/aibnd_lib/rtl/block_function/aibnd_dll_phdet.v
../maib_rtl/aibnd_lib/rtl/block_function/aibnd_dll_custom.v
../maib_rtl/aibnd_lib/rtl/block_function/aibnd_inv_split_align.v
../maib_rtl/aibnd_lib/rtl/block_function/aibnd_quadph_code_gen.v
../maib_rtl/aibnd_lib/rtl/block_function/aibnd_preclkbuf.v
../maib_rtl/aibnd_lib/rtl/block_function/aibnd_rxdatapath_rx.v
../maib_rtl/aibnd_lib/rtl/block_function/aibnd_rxdig.v
../maib_rtl/aibnd_lib/rtl/block_function/aibnd_str_align.v
../maib_rtl/aibnd_lib/rtl/block_function/aibnd_txdatapath_tx.v
../maib_rtl/aibnd_lib/rtl/block_function/aibnd_txdig.v
../maib_rtl/aibnd_lib/rtl/block_function/aibnd_rxanlg.v
../maib_rtl/aibnd_lib/rtl/block_function/aibnd_txanlg.v
../maib_rtl/aibnd_lib/rtl/block_function/aibnd_dcc_fine_dly_x1.v
../maib_rtl/aibnd_lib/rtl/block_function/aibnd_fine_dly_x1.v
../maib_rtl/aibnd_lib/rtl/block_function/aibnd_dcc_dly_inv.v
../maib_rtl/aibnd_lib/rtl/block_function/aibnd_fine_dly_inv.v
../maib_rtl/aibnd_lib/rtl/block_function/aibnd_str_ff.v
../maib_rtl/aibnd_lib/rtl/block_function/aibnd_dcc_helper.v
../maib_rtl/aibnd_lib/rtl/block_function/aibnd_str_clktree_mimic.v
../maib_rtl/aibnd_lib/rtl/block_function/aibnd_dcc_dly.v
../maib_rtl/aibnd_lib/rtl/block_function/aibnd_red_custom_dig.v
../maib_rtl/aibnd_lib/rtl/block_function/aibnd_str_preclkbuf.v
../maib_rtl/aibnd_lib/rtl/block_function/aibnd_nand_x64_delay_line.v
../maib_rtl/aibnd_lib/rtl/block_function/aibnd_str_clktree.v
../maib_rtl/aibnd_lib/rtl/block_function/aibnd_sync_ff.v
../maib_rtl/aibnd_lib/rtl/block_function/aibnd_cmos_nand_x64.v
../maib_rtl/aibnd_lib/rtl/block_function/aibnd_signal_buf.v
../maib_rtl/aibnd_lib/rtl/block_function/aibnd_red_custom_dig2.v
../maib_rtl/aibnd_lib/rtl/block_function/aibnd_avmm_rst_sync.v
../maib_rtl/aibnd_lib/rtl/block_function/aibnd_data_buf.v
../maib_rtl/aibnd_lib/rtl/block_function/aibnd_interface.v
../maib_rtl/aibnd_lib/rtl/block_function/aibnd_rambit_buf.v
../maib_rtl/aibnd_lib/rtl/block_function/aibnd_inv.v
../maib_rtl/aibnd_lib/rtl/block_function/aibnd_nand2.v
../maib_rtl/aibnd_lib/rtl/block_function/aibnd_nor2.v
../maib_rtl/aibnd_lib/rtl/block_function/aibnd_red_clkmux2.v
../maib_rtl/aibnd_lib/rtl/block_function/aibnd_red_clkmux3.v
../maib_rtl/aibnd_lib/rtl/block_function/aibnd_txdat_mimic.v
../maib_rtl/aibnd_lib/rtl/block_function/aibnd_rxdat_mimic.v
../maib_rtl/aibnd_lib/rtl/block_function/aibnd_clkmux2.v
//Looks fine to me. All behavior and from Nightfury

../maib_rtl/io_common_custom/rtl/block_function/io_interp_mux.v
../maib_rtl/io_common_custom/rtl/block_function/io_ip16phs.v
../maib_rtl/io_common_custom/rtl/block_function/io_cmos_16ph_decode.v
../maib_rtl/io_common_custom/rtl/block_function/io_interp_misc.v
../maib_rtl/io_common_custom/rtl/block_function/io_interp_output.v
../maib_rtl/io_common_custom/rtl/block_function/io_interp_latch_in.v
../maib_rtl/io_common_custom/rtl/block_function/io_interp_mux_pair.v
../maib_rtl/io_common_custom/rtl/block_function/io_interp_pdn.v
../maib_rtl/io_common_custom/rtl/block_function/io_min_interp_mux.v
../maib_rtl/io_common_custom/rtl/block_function/io_min_ip16phs.v
../maib_rtl/io_common_custom/rtl/block_function/io_min_output.v
../maib_rtl/io_common_custom/rtl/block_function/io_min_misc.v
../maib_rtl/io_common_custom/rtl/block_function/io_min_pdn.v
../maib_rtl/io_common_custom/rtl/block_function/io_dly_interpolator.v
../maib_rtl/io_common_custom/rtl/block_function/io_dly_interpclk.v
../maib_rtl/io_common_custom/rtl/block_function/io_ip8phs_3in.v
../maib_rtl/io_common_custom/rtl/block_function/io_cmos_nand_x1.v
../maib_rtl/io_common_custom/rtl/block_function/io_cmos_nand_x128.v
../maib_rtl/io_common_custom/rtl/block_function/io_cmos_nand_x64_decode.v
../maib_rtl/io_common_custom/rtl/block_function/io_cmos_nand_x128_decode.v
../maib_rtl/io_common_custom/rtl/block_function/io_cmos_nand_x6.v
../maib_rtl/io_common_custom/rtl/block_function/io_nand_x128_delay_line.v
../maib_rtl/io_common_custom/rtl/block_function/io_cmos_nand_x64.v
../maib_rtl/io_common_custom/rtl/block_function/io_cmos_nand_x4.v
../maib_rtl/io_common_custom/rtl/block_function/io_split_align.v
../maib_rtl/io_common_custom/rtl/block_function/io_dll_phdet.v
../maib_rtl/io_common_custom/rtl/block_function/io_nand_delay_line_min.v
../maib_rtl/soc_std_macro/rtl/block_function/i14socnd/soc_simulation_defines.v
// Not used
// Standard Cell, OK to use with ALTR_HPS_INTEL_MACROS_OFF option
../maib_rtl/soc_std_macro/rtl/block_function/i14socnd/altr_hps_ckinv.v
../maib_rtl/soc_std_macro/rtl/block_function/i14socnd/altr_hps_ckmux21.v
../maib_rtl/aibndpnr_lib/rtl/block_function/aibndpnr_redundancy.v
../maib_rtl/aibndpnr_lib/rtl/block_function/aibndpnr_jtag_bscan.v
../maib_rtl/aibndpnr_lib/rtl/block_function/aibndpnr_bsr_red_wrap.v
../maib_rtl/aibndpnr_lib/rtl/block_function/aibndpnr_half_cycle_code_gen.v
../maib_rtl/aibndpnr_lib/rtl/block_function/aibndpnr_self_lock_assertion.v
../maib_rtl/aibndpnr_lib/rtl/block_function/aibndpnr_dll_ctrl.v
../maib_rtl/aibndpnr_lib/rtl/block_function/aibndpnr_dll_core.v
../maib_rtl/aibndpnr_lib/rtl/block_function/aibndpnr_dll_pnr.v
../maib_rtl/aibndpnr_lib/rtl/block_function/aibndpnr_dll_atech_clkgate_cgc00.v
../maib_rtl/aibndpnr_lib/rtl/block_function/aibndpnr_dll_atech_clkgate_cgc01.v
../maib_rtl/aibndpnr_lib/rtl/block_function/aibndpnr_dll_atech_clkmux.v
