wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt.v

wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_avmm/hdpldadapt_avmm1_async.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_avmm/hdpldadapt_avmm1_config.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_avmm/hdpldadapt_avmm1_dprio_mapping.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_avmm/hdpldadapt_avmm1_transfer.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_avmm/hdpldadapt_avmm1.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_avmm/hdpldadapt_avmm2_async.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_avmm/hdpldadapt_avmm2_transfer.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_avmm/hdpldadapt_avmm2.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_avmm/hdpldadapt_avmm_async_update.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_avmm/hdpldadapt_avmmclk_ctl.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_avmm/hdpldadapt_avmm_cmdfifo.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_avmm/hdpldadapt_avmm_cmn_intf.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_avmm/hdpldadapt_avmm_dprio_reg.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_avmm/hdpldadapt_avmm_rdfifo.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_avmm/hdpldadapt_avmmrst_ctl.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_avmm/hdpldadapt_avmm.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_avmm/hdpldadapt_avmm_async.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_avmm/hdpldadapt_hrdrst_rstctrl.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_avmm/hdpldadapt_hrdrst_clkctl.v

wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_sr/hdpldadapt_fsr_in.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_sr/hdpldadapt_fsr_out.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_sr/hdpldadapt_srclk_ctl.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_sr/hdpldadapt_sr_in_bit.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_sr/hdpldadapt_sr_out_bit.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_sr/hdpldadapt_srrst_ctl.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_sr/hdpldadapt_sr_sm.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_sr/hdpldadapt_sr.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_sr/hdpldadapt_ssr_in.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_sr/hdpldadapt_ssr_out.v

wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_tx_chnl/hdpldadapt_async_update.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_tx_chnl/hdpldadapt_tx_async_reserved_capture.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_tx_chnl/hdpldadapt_tx_async_reserved_update.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_tx_chnl/hdpldadapt_hip_async_capture.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_tx_chnl/hdpldadapt_hip_async_update.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_tx_chnl/hdpldadapt_tx_async_capture.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_tx_chnl/hdpldadapt_tx_async_direct.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_tx_chnl/hdpldadapt_tx_async_update.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_tx_chnl/hdpldadapt_tx_async.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_tx_chnl/hdpldadapt_tx_chnl.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_tx_chnl/hdpldadapt_txclk_ctl.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_tx_chnl/hdpldadapt_tx_datapath_async_fifo.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_tx_chnl/hdpldadapt_tx_datapath_fifo_ram.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_tx_chnl/hdpldadapt_tx_datapath_fifo_pointers.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_tx_chnl/hdpldadapt_tx_chnl_testbus.v

wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_tx_chnl/hdpldadapt_tx_datapath_cp_bond.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_tx_chnl/hdpldadapt_tx_datapath_dv_gen.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_tx_chnl/hdpldadapt_tx_datapath_fifo.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_tx_chnl/hdpldadapt_tx_datapath_frame_gen.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_tx_chnl/hdpldadapt_tx_datapath.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_tx_chnl/hdpldadapt_tx_datapath_word_mark.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_tx_chnl/hdpldadapt_txrst_ctl.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_tx_chnl/hdpldadapt_tx_datapath_pulse_stretch.v

wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_rx_chnl/hdpldadapt_rx_async_reserved_capture.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_rx_chnl/hdpldadapt_rx_async_reserved_update.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_rx_chnl/hdpldadapt_rx_async_capture.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_rx_chnl/hdpldadapt_rx_async_direct.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_rx_chnl/hdpldadapt_rx_async_update.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_rx_chnl/hdpldadapt_rx_async.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_rx_chnl/hdpldadapt_rx_chnl.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_rx_chnl/hdpldadapt_rxclk_ctl.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_rx_chnl/hdpldadapt_rx_datapath_asn.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_rx_chnl/hdpldadapt_rx_datapath_async_fifo.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_rx_chnl/hdpldadapt_rx_datapath_cp_bond.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_rx_chnl/hdpldadapt_rx_datapath_fifo.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_rx_chnl/hdpldadapt_rx_datapath_fifo_ram.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_rx_chnl/hdpldadapt_rx_datapath_fifo_pointers.v

wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_rx_chnl/hdpldadapt_rx_datapath_insert_sm.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_rx_chnl/hdpldadapt_rx_datapath_del_sm.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_rx_chnl/hdpldadapt_rx_datapath.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_rx_chnl/hdpldadapt_rx_datapath_word_align.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_rx_chnl/hdpldadapt_rxrst_ctl.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_rx_chnl/hdpldadapt_rx_datapath_pulse_stretch.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_rx_chnl/hdpldadapt_rx_chnl_testbus.v


wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_cmn/hdpldadapt_cmn_async_capture_bit.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_cmn/hdpldadapt_cmn_cp_comp_cntr.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_cmn/hdpldadapt_cmn_cp_dist_pair_dw.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_cmn/hdpldadapt_cmn_cp_dist.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_cmn/hdpldadapt_cmn_async_capture_bus.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_cmn/hdpldadapt_cmn_cp_dist_dw.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_cmn/hdpldadapt_cmn_cp_dist_pair.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_cmn/hdpldadapt_cmn_latency_measure.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_cmn/hdpldadapt_cmn_pulse_stretch.v

wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_cmn/hdpldadapt_cmn_parity_gen.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_cmn/hdpldadapt_cmn_parity_checker.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_cmn/hdpldadapt_cmn_clkand2.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_cmn/hdpldadapt_cmn_clkdelay_map.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_cmn/hdpldadapt_cmn_clkdelay.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_cmn/hdpldadapt_cmn_clkdelay_cell.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_cmn/hdpldadapt_cmn_clkgate.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_cmn/hdpldadapt_cmn_clkinv.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_cmn/hdpldadapt_cmn_clkmux2_cell.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_cmn/hdpldadapt_cmn_clkmux2.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_cmn/hdpldadapt_cmn_clkor2.v
//wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_cmn/hdpldadapt_cmn_dft_clock_controller.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_cmn/hdpldadapt_cmn_occ_clkgate.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_cmn/hdpldadapt_cmn_occ_enable_logic.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_cmn/hdpldadapt_cmn_occ_gray_code_counter.v
wkspace_root/hdpldadapt/rtl/block_function/hdpldadapt_cmn/hdpldadapt_cmn_occ_test_control_register.v

-f wkspace_root/soc_common/rtl/filelists/syn/soc_common.f
-f wkspace_root/cdclib/rtl/filelists/syn/cdclib_bintogray.f
-f wkspace_root/cdclib/rtl/filelists/syn/cdclib_bintogray_inc8.f
-f wkspace_root/cdclib/rtl/filelists/syn/cdclib_bitsync2.f
-f wkspace_root/cdclib/rtl/filelists/syn/cdclib_bitsync4.f
-f wkspace_root/cdclib/rtl/filelists/syn/cdclib_graytobin.f
-f wkspace_root/cdclib/rtl/filelists/syn/cdclib_graytobin_inc2.f
-f wkspace_root/cdclib/rtl/filelists/syn/cdclib_graytobin_inc8.f
-f wkspace_root/cdclib/rtl/filelists/syn/cdclib_rst_n_sync.f
-f wkspace_root/cfg_shared/rtl/filelists/syn/cfg_dprio_csr_reg_nregs.f
-f wkspace_root/cfg_shared/rtl/filelists/syn/cfg_dprio_ctrl_stat_interface_top.f
-f wkspace_root/cfg_shared/rtl/filelists/syn/cfg_dprio_ctrl_stat_reg_top.f
-f wkspace_root/cfg_shared/rtl/filelists/syn/cfg_dprio_shadow_status_regs.f
