+incdir+${AIB2_RTL_ROOT}
${AIB2_RTL_ROOT}/ana_models/msv_models/aibio_dqs_dcs_cbb.sv
${AIB2_RTL_ROOT}/ana_models/msv_models/aibio_adc_cbb.sv
${AIB2_RTL_ROOT}/ana_models/msv_models/aibio_clkdist_inv1_cbb.sv
${AIB2_RTL_ROOT}/ana_models/msv_models/aibio_clkdist_inv2_cbb.sv
${AIB2_RTL_ROOT}/ana_models/msv_models/aibio_rxclk_cbb.sv
${AIB2_RTL_ROOT}/ana_models/msv_models/aibio_vref_cbb.sv
${AIB2_RTL_ROOT}/ana_models/msv_models/TXRX/aibio_txrx_cbb.sv
${AIB2_RTL_ROOT}/ana_models/msv_models/TXRX/en_logic_xxpad.sv
${AIB2_RTL_ROOT}/ana_models/msv_models/TXRX/pad_out_logic.sv
${AIB2_RTL_ROOT}/ana_models/msv_models/TXRX/sampler.sv
${AIB2_RTL_ROOT}/ana_models/msv_models/DLL/aibio_decoder2x4.sv
${AIB2_RTL_ROOT}/ana_models/msv_models/DLL/aibio_decoder3x8.sv
${AIB2_RTL_ROOT}/ana_models/msv_models/DLL/aibio_dll_top.sv
${AIB2_RTL_ROOT}/ana_models/msv_models/DLL/aibio_lock_detector.sv
${AIB2_RTL_ROOT}/ana_models/msv_models/DLL/aibio_outclk_mux16x1.sv
${AIB2_RTL_ROOT}/ana_models/msv_models/DLL/aibio_outclk_select.sv
${AIB2_RTL_ROOT}/ana_models/msv_models/DLL/aibio_piclk_dist.sv
${AIB2_RTL_ROOT}/ana_models/msv_models/DLL/aibio_pimux4x1.sv
${AIB2_RTL_ROOT}/ana_models/msv_models/DLL/aibio_se_to_diff.sv
${AIB2_RTL_ROOT}/ana_models/msv_models/DLL/RX_DLL/aibio_3bit_bin_to_therm.sv
${AIB2_RTL_ROOT}/ana_models/msv_models/DLL/RX_DLL/aibio_4bit_plus1.sv
${AIB2_RTL_ROOT}/ana_models/msv_models/DLL/RX_DLL/aibio_bias_trim.sv
${AIB2_RTL_ROOT}/ana_models/msv_models/DLL/RX_DLL/aibio_cdr_detect.sv
${AIB2_RTL_ROOT}/ana_models/msv_models/DLL/RX_DLL/aibio_half_adder.sv
${AIB2_RTL_ROOT}/ana_models/msv_models/DLL/RX_DLL/aibio_inpclk_select.sv
${AIB2_RTL_ROOT}/ana_models/msv_models/DLL/RX_DLL/aibio_pi_codeupdate.sv
${AIB2_RTL_ROOT}/ana_models/msv_models/DLL/RX_DLL/aibio_pi_decode.sv
${AIB2_RTL_ROOT}/ana_models/msv_models/DLL/RX_DLL/aibio_pi_decode_sync.sv
${AIB2_RTL_ROOT}/ana_models/msv_models/DLL/RX_DLL/aibio_pi_mixer_top.sv
${AIB2_RTL_ROOT}/ana_models/msv_models/DLL/RX_DLL/aibio_pioddevn_mixer_top.sv
${AIB2_RTL_ROOT}/ana_models/msv_models/DLL/RX_DLL/aibio_pioddevn_phsel_half.sv
${AIB2_RTL_ROOT}/ana_models/msv_models/DLL/RX_DLL/aibio_pioddevn_top.sv
${AIB2_RTL_ROOT}/ana_models/msv_models/DLL/RX_DLL/aibio_pi_phsel_halfside.sv
${AIB2_RTL_ROOT}/ana_models/msv_models/DLL/RX_DLL/aibio_pi_phsel_quarter.sv
${AIB2_RTL_ROOT}/ana_models/msv_models/DLL/RX_DLL/aibio_rxdll_cbb.sv
${AIB2_RTL_ROOT}/ana_models/msv_models/DLL/TX_DLL/aibio_inpclk_select_txdll.sv
${AIB2_RTL_ROOT}/ana_models/msv_models/DLL/TX_DLL/aibio_pulsegen_mux2x1.sv
${AIB2_RTL_ROOT}/ana_models/msv_models/DLL/TX_DLL/aibio_pulsegen_mux8x1.sv
${AIB2_RTL_ROOT}/ana_models/msv_models/DLL/TX_DLL/aibio_pulsegen_muxfinal.sv
${AIB2_RTL_ROOT}/ana_models/msv_models/DLL/TX_DLL/aibio_pulsegen_oddevn_halfside.sv
${AIB2_RTL_ROOT}/ana_models/msv_models/DLL/TX_DLL/aibio_pulsegen_phsel_halfside.sv
${AIB2_RTL_ROOT}/ana_models/msv_models/DLL/TX_DLL/aibio_pulsegen_top.sv
${AIB2_RTL_ROOT}/ana_models/msv_models/DLL/TX_DLL/aibio_txdll_cbb.sv
${AIB2_RTL_ROOT}/ana_models/msv_models/AUX_CH/aibio_auxch_cbb.sv
${AIB2_RTL_ROOT}/ana_models/msv_models/AUX_CH/aibio_auxch_Schmit_trigger.sv
${AIB2_RTL_ROOT}/ana_models/msv_models/PVTMON/aibio_pvtmon_3to8dec.sv
${AIB2_RTL_ROOT}/ana_models/msv_models/PVTMON/aibio_pvtmon_cbb.sv
${AIB2_RTL_ROOT}/ana_models/msv_models/PVTMON/aibio_pvtmon_clk_divby2.sv
${AIB2_RTL_ROOT}/ana_models/msv_models/PVTMON/aibio_pvtmon_clkdiv.sv
${AIB2_RTL_ROOT}/ana_models/msv_models/PVTMON/aibio_pvtmon_ctr10b.sv
${AIB2_RTL_ROOT}/ana_models/msv_models/PVTMON/aibio_pvtmon_ctrunit.sv
${AIB2_RTL_ROOT}/ana_models/msv_models/PVTMON/aibio_pvtmon_dig.sv
${AIB2_RTL_ROOT}/ana_models/msv_models/PVTMON/aibio_pvtmon_digview.sv
${AIB2_RTL_ROOT}/ana_models/msv_models/PVTMON/aibio_pvtmon_ndmnn11.sv
${AIB2_RTL_ROOT}/ana_models/msv_models/PVTMON/aibio_pvtmon_oscbank.sv
${AIB2_RTL_ROOT}/ana_models/msv_models/PVTMON/aibio_pvtmon_pdmpp11.sv
${AIB2_RTL_ROOT}/ana_models/msv_models/PVTMON/flop.sv
${AIB2_RTL_ROOT}/ana_models/msv_models/PVTMON/mux2x1.sv
${AIB2_RTL_ROOT}/src/rtl/common/aib_bit_sync.v
${AIB2_RTL_ROOT}/src/rtl/common/aib_bus_sync.v
${AIB2_RTL_ROOT}/src/rtl/common/aib_rst_sync.v
${AIB2_RTL_ROOT}/src/rtl/common/aib_adapt_fifo_mem.v
${AIB2_RTL_ROOT}/src/rtl/common/aib_adapt_fifo_ptr.v
${AIB2_RTL_ROOT}/src/rtl/common/aib_clk_div.v
${AIB2_RTL_ROOT}/src/rtl/common/aib_fifo_and_sel.v
${AIB2_RTL_ROOT}/src/rtl/common/aib_fifo_rdata_ored.sv
${AIB2_RTL_ROOT}/src/rtl/common/aib_fifo_rdata_buf.v
${AIB2_RTL_ROOT}/src/rtl/common/aib_clk_div_sys.v
${AIB2_RTL_ROOT}/src/rtl/common/aib_clk_div_roffcal.v
${AIB2_RTL_ROOT}/src/rtl/common/aib_clk_div_rcomp.v
${AIB2_RTL_ROOT}/src/rtl/common/aib_clk_div_dcs.v
${AIB2_RTL_ROOT}/src/rtl/common/aib_bs_clk_gating.v
${AIB2_RTL_ROOT}/src/rtl/common/aib_bscan.v
${AIB2_RTL_ROOT}/src/rtl/aibadapt/aibadapt_rxchnl/aib_rx_bert.v
${AIB2_RTL_ROOT}/src/rtl/aibadapt/aibadapt_rxchnl/aib_bert_chk.v
${AIB2_RTL_ROOT}/src/rtl/aibadapt/aibadapt_txchnl/aib_tx_bert.sv
${AIB2_RTL_ROOT}/src/rtl/aibadapt/aibadapt_txchnl/aib_bert_gen.v
${AIB2_RTL_ROOT}/src/rtl/common/aib_bert_cdc.v
${AIB2_RTL_ROOT}/behavior/clk_mux.v
${AIB2_RTL_ROOT}/behavior/clk_gate_cel.v
${AIB2_RTL_ROOT}/behavior/clk_or2_cel.v
${AIB2_RTL_ROOT}/behavior/clk_or3_cel.v
${AIB2_RTL_ROOT}/behavior/clk_and2_cel.v
${AIB2_RTL_ROOT}/behavior/clk_and3_cel.v
${AIB2_RTL_ROOT}/behavior/clk_and4_cel.v
${AIB2_RTL_ROOT}/behavior/clk_den_flop.v
${AIB2_RTL_ROOT}/behavior/clk_inv_cel.v
${AIB2_RTL_ROOT}/behavior/dmux_cell.v
${AIB2_RTL_ROOT}/behavior/clk_buf_cel.v
${AIB2_RTL_ROOT}/behavior/clk_resize_cel.v
${AIB2_RTL_ROOT}/src/rtl/common/aib_cdc_data_mux.v
${AIB2_RTL_ROOT}/src/rtl/aibadapt/aibadapt_sr/aib_sr_fsm.v
${AIB2_RTL_ROOT}/src/rtl/aibadapt/aibadapt_sr/aib_sr_master.v
${AIB2_RTL_ROOT}/src/rtl/aibadapt/aibadapt_sr/aib_sr_slave.v
${AIB2_RTL_ROOT}/src/rtl/aibadapt/aibadapt_rxchnl/aib_rxfifo_rdata_sel.sv
${AIB2_RTL_ROOT}/src/rtl/aibadapt/aibadapt_rxchnl/aib_rxfifo_clk_gating.v
${AIB2_RTL_ROOT}/src/rtl/aibadapt/aibadapt_txchnl/aib_txfifo_clk_gating.v
${AIB2_RTL_ROOT}/src/rtl/aibadapt/aibadapt_rxchnl/aib_rxfifo_rd_dpath.sv
${AIB2_RTL_ROOT}/src/rtl/aibadapt/aibadapt_txchnl/aib_txfifo_rd_dpath.sv
${AIB2_RTL_ROOT}/src/rtl/aibadapt/aibadapt_rxchnl/aib_adapter_rxchnl.v
${AIB2_RTL_ROOT}/src/rtl/aibadapt/aibadapt_txchnl/aib_adapter_txchnl.v
${AIB2_RTL_ROOT}/src/rtl/aibadapt/aibadapt_rxchnl/aib_rx_dbi.v
${AIB2_RTL_ROOT}/src/rtl/aibadapt/aibadapt_rxchnl/aib_rx_fifo_wam.v
${AIB2_RTL_ROOT}/src/rtl/aibadapt/aibadapt_rxchnl/aib_adapt_rx_fifo.v
${AIB2_RTL_ROOT}/src/rtl/aibadapt/aibadapt_txchnl/aib_tx_dbi.v
${AIB2_RTL_ROOT}/src/rtl/aibadapt/aibadapt_txchnl/aib_adapt_tx_fifo.v
${AIB2_RTL_ROOT}/src/rtl/aibadapt/aib_adapter.v
${AIB2_RTL_ROOT}/src/rtl/aibadapt/aibadapt_avmm/aib_avalon_if.sv
${AIB2_RTL_ROOT}/src/rtl/aibadapt/aibadapt_avmm/aib_avalon_adapt_reg.v
${AIB2_RTL_ROOT}/src/rtl/aibadapt/aibadapt_avmm/aib_avalon_io_regs.v
${AIB2_RTL_ROOT}/src/rtl/aibadapt/aibadapt_avmm/aib_avalon.v
${AIB2_RTL_ROOT}/src/rtl/aib_fsm/aib_cdr_fsm.v
${AIB2_RTL_ROOT}/src/rtl/aib_fsm/phase_adjust_fsm.v
${AIB2_RTL_ROOT}/src/rtl/aib_fsm/phase_adjust_fsm_top.v
//${AIB2_RTL_ROOT}/src/rtl/aib_fsm/rx_offset_cal_fsm.v
${AIB2_RTL_ROOT}/src/rtl/aib_fsm/rx_offset_cal_fsm_top.v
${AIB2_RTL_ROOT}/src/rtl/aib_fsm/rx_offset_cal.v
${AIB2_RTL_ROOT}/src/rtl/aib_fsm/rxoffset_top.v
${AIB2_RTL_ROOT}/src/rtl/aib_fsm/rcomp_calibration_fsm.v
${AIB2_RTL_ROOT}/src/rtl/aib_fsm/aib_ntl_fsm.v
${AIB2_RTL_ROOT}/src/rtl/aib_fsm/aib_dcs_fsm.v
${AIB2_RTL_ROOT}/src/rtl/aib_fsm/aib_dfx_mon.v
${AIB2_RTL_ROOT}/src/rtl/aib_top/aib_channel_n.v
${AIB2_RTL_ROOT}/src/rtl/aib_top/aibio_ana_top.v
${AIB2_RTL_ROOT}/src/rtl/redundancy/aib_redundancy.v
${AIB2_RTL_ROOT}/src/rtl/redundancy/aib_redundancy_wrp.v
${AIB2_RTL_ROOT}/src/rtl/redundancy/aib_redundancy_wrp_top.v
${AIB2_RTL_ROOT}/src/rtl/aib_top/aib_deskew_logic.v
${AIB2_RTL_ROOT}/src/rtl/aib_fsm/aib_dll_ctrl_logic.v
${AIB2_RTL_ROOT}/src/rtl/aib_top/aib_avmm_glue_logic.sv
${AIB2_RTL_ROOT}/src/rtl/aib_top/aib_avmm_top.v
${AIB2_RTL_ROOT}/src/rtl/aib_top/aib_phy_top.v
