#!/bin/bash


export RTL_ROOT="$(pwd)/../../../rev1/rtl"
export GEN1_ROOT="$(pwd)/../../../../v1.0/rev2/rtl"
export V1M_ROOT="$GEN1_ROOT/v1_master"
export V2COM_ROOT="$GEN1_ROOT/v2_common"
export FM_ROOT="$(pwd)/../../rtl/maib_rev1.1"
export REV1_DV="$(pwd)/../../../rev1/dv"
export AIB2_RTL_ROOT="/nfs/sc/disks/psg_sailrock_1/users/huizhan1/sailrock/wsp/BCA/D12_candidate_front_end/digital"

vlogan -sverilog  +v2k -full64 -timescale=1ps/1ps -f ../flist/AIB2.0_RTL_filelist.f -l compile_ms1.log
vlogan -sverilog  +v2k -full64 -timescale=1ps/1ps +define+VCS+AIB_TOP_PIN96+TIMESCALE_EN+BEHAVIORAL  -f $REV1_DV/flist/ms_v1.cf -l compile_ms_gen1.log

vlogan -sverilog  +v2k -full64  -timescale=1ps/1ps +define+VCS+SL_AIB_BCA+MS_AIB_GEN1 -f ../flist/tb_rtl.cf -l compile_tb.log

vcs -debug_acc+all -full64 +lint=TFIPC-L +error+100 +lint=PCWM  -top top_tb -l vcs.log
