#!/bin/bash


export RTL_ROOT="$(pwd)/../../../rev1/rtl"
export GEN1_ROOT="$(pwd)/../../../../v1.0/rev2/rtl"
export V1S_ROOT="$GEN1_ROOT/v1_slave"
export V2COM_ROOT="$GEN1_ROOT/v2_common"
export FM_ROOT="$(pwd)/../../rtl/maib_rev1.1"
export REV1_DV="$(pwd)/../../../rev1/dv"
export AIB2_RTL_ROOT="../../rtl/bca"

#vlogan -sverilog  +v2k -full64 -timescale=1ps/1ps -f $AIB2_RTL_ROOT/AIB2.0_RTL_filelist.f -f $REV1_DV/flist/ms.cf -l compile_ms1.log

#vlogan -sverilog  +v2k -full64  -timescale=1ps/1ps +define+VCS+SL_AIB_BCA+MS_AIB_BCA -f ../flist/tb_rtl.cf -l compile_tb.log

#vcs -debug_acc+all -full64 +lint=TFIPC-L +error+100 +lint=PCWM  -top top_tb -l vcs.log

xrun -sv -timescale 1ps/1ps -f $AIB2_RTL_ROOT/AIB2.0_RTL_filelist.f -f $REV1_DV/flist/ms.cf +define+SL_AIB_BCA+MS_AIB_BCA -f ../flist/tb_rtl.cf -access rwc -input sim_input.tcl
