    //=================================================================================
    // Slave AIB IOs
    //=================================================================================
    wire [101:0] m1_iopad_ch0_aib;
    wire [101:0] s1_iopad_ch0_aib;
    wire [101:0] m1_iopad_ch1_aib;
    wire [101:0] s1_iopad_ch1_aib;
    wire [101:0] m1_iopad_ch2_aib;
    wire [101:0] s1_iopad_ch2_aib;
    wire [101:0] m1_iopad_ch3_aib;
    wire [101:0] s1_iopad_ch3_aib;
    wire [101:0] m1_iopad_ch4_aib;
    wire [101:0] s1_iopad_ch4_aib;
    wire [101:0] m1_iopad_ch5_aib;
    wire [101:0] s1_iopad_ch5_aib;
    wire [101:0] m1_iopad_ch6_aib;
    wire [101:0] s1_iopad_ch6_aib;
    wire [101:0] m1_iopad_ch7_aib;
    wire [101:0] s1_iopad_ch7_aib;
    wire [101:0] m1_iopad_ch8_aib;
    wire [101:0] s1_iopad_ch8_aib;
    wire [101:0] m1_iopad_ch9_aib;
    wire [101:0] s1_iopad_ch9_aib;
    wire [101:0] m1_iopad_ch10_aib;
    wire [101:0] s1_iopad_ch10_aib;
    wire [101:0] m1_iopad_ch11_aib;
    wire [101:0] s1_iopad_ch11_aib;
    wire [101:0] m1_iopad_ch12_aib;
    wire [101:0] s1_iopad_ch12_aib;
    wire [101:0] m1_iopad_ch13_aib;
    wire [101:0] s1_iopad_ch13_aib;
    wire [101:0] m1_iopad_ch14_aib;
    wire [101:0] s1_iopad_ch14_aib;
    wire [101:0] m1_iopad_ch15_aib;
    wire [101:0] s1_iopad_ch15_aib;
    wire [101:0] m1_iopad_ch16_aib;
    wire [101:0] s1_iopad_ch16_aib;
    wire [101:0] m1_iopad_ch17_aib;
    wire [101:0] s1_iopad_ch17_aib;
    wire [101:0] m1_iopad_ch18_aib;
    wire [101:0] s1_iopad_ch18_aib;
    wire [101:0] m1_iopad_ch19_aib;
    wire [101:0] s1_iopad_ch19_aib;
    wire [101:0] m1_iopad_ch20_aib;
    wire [101:0] s1_iopad_ch20_aib;
    wire [101:0] m1_iopad_ch21_aib;
    wire [101:0] s1_iopad_ch21_aib;
    wire [101:0] m1_iopad_ch22_aib;
    wire [101:0] s1_iopad_ch22_aib;
    wire [101:0] m1_iopad_ch23_aib;
    wire [101:0] s1_iopad_ch23_aib;
    //=================================================================================
    // Register config for testbench 
    //=================================================================================
    reg  [1:0]  ms1_tx_fifo_mode;
    reg  [1:0]  sl1_tx_fifo_mode;
    reg  [1:0]  ms1_rx_fifo_mode;
    reg  [1:0]  sl1_rx_fifo_mode;
    reg  [4:0]  ms1_tx_markbit;
    reg  [4:0]  sl1_tx_markbit;
